---

- name: Ensure bash directories exist
  become: "{{ outer_item.become }}"
  ansible.builtin.file:
    path: "{{ outer_item.bashrc_d_dir }}"
    mode: "{{ outer_item.directory_mode }}"
    owner: "{{ outer_item.owner }}"
    group: "{{ outer_item.owner }}"
    state: directory

- name: Copy bash configuration files
  become: "{{ outer_item.become }}"
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ outer_item.mode }}"
    directory_mode: "{{ outer_item.directory_mode }}"
    owner: "{{ outer_item.owner }}"
    group: "{{ outer_item.owner }}"
  loop:
    - src: bashrc
      dest: "{{ outer_item.bashrc }}"
    - src: bash_profile
      dest: "{{ outer_item.bash_profile }}"
    - src: bash_logout
      dest: "{{ outer_item.bash_logout }}"
    - src: bashrc.d/
      dest: "{{ outer_item.bashrc_d_dir }}/"

- name: Symlink helper files
  become: "{{ outer_item.become }}"
  ansible.builtin.file:
    src: "{{ item.src }}"
    dest: "{{ outer_item.bashrc_d_dir }}/{{ item.name }}"
    state: link
  loop:
    - src: "{{ git_prompt_sh }}"
      name: "git-prompt.sh"
    - src: "{{ vte_sh }}"
      name: "vte.sh"

# vim: ft=yaml.ansible
