---

- name: Configure Linux and apply dotfiles
  hosts: all
  gather_facts: true

  roles:
    - role: dnf
    - role: git
    - role: emacs
    - role: nvim
    - role: tmux
    - role: gnome
    - role: ssh
    - role: shell

# vim: ft=yaml.ansible
