---

# Install Fedora group packages
- name: Install group packages
  when: ansible_distribution == "Fedora"
  become: true
  ansible.builtin.dnf:
    name: "{{ group_packages }}"
    state: present

# vim: ft=yaml.ansible
