---

# Same as `dnf up`
- name: Update all packages
  when: ansible_facts['distribution'] == "Fedora"
  become: true
  ansible.builtin.dnf:
    name: "*"
    state: latest

# Same as `zypper dup`
- name: Update all packages
  when: ansible_facts['distribution'] == "OpenSuse"
  become: true
  community.general.zypper:
    name: "*"
    state: dist-upgrade

# Same as `pacman -Syu`
- name: Update all packages
  when: ansible_facts['distribution'] == "ArchLinux"
  become: true
  community.general.pacman:
    update_cache: true
    upgrade: true

# vim: ft=yaml.ansible
