---

- name: Configure bash
  block:
    # {{{ Ensure directories exist
    - name: Ensure "~/.bashrc.d" directory exists
      ansible.builtin.file:
        path: "{{ outer_item.home_path }}/.bashrc.d"
        mode: "{{ outer_item.directory_mode }}"
        owner: "{{ outer_item.become_user }}"
        group: "{{ outer_item.become_user }}"
        state: directory
      become: true
      become_user: "{{ outer_item.become_user }}"
    # }}}

    # {{{ Copy configuration files
    - name: Copy bash configuration files
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: "{{ outer_item.mode }}"
        directory_mode: "{{ outer_item.directory_mode }}"
        owner: "{{ outer_item.become_user }}"
        group: "{{ outer_item.become_user }}"
      loop:
        - src: files/bashrc
          dest: "{{ outer_item.home_path }}/.bashrc"
        - src: files/bash_profile
          dest: "{{ outer_item.home_path }}/.bash_profile"
        - src: files/bash_logout
          dest: "{{ outer_item.home_path }}/.bash_logout"
        - src: files/bashrc.d/
          dest: "{{ outer_item.home_path }}/.bashrc.d/"
      become: true
      become_user: "{{ outer_item.become_user }}"
    # }}}

    # {{{ Symlink bash helper files
    - name: Symlink "git-prompt.sh"
      ansible.builtin.file:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        state: link
        force: true
      loop:
        - src: /usr/share/git-core/contrib/completion/git-prompt.sh
          dest: "{{ outer_item.home_path }}/.bashrc.d/git-prompt.sh"
        - src: /etc/profile.d/vte.sh
          dest: "{{ outer_item.home_path }}/.bashrc.d/vte.sh"
      become: true
      become_user: "{{ outer_item.become_user }}"
    # }}}

# vim: fdm=marker
