---

# {{{ Configure user's bash
- name: Configure user's bash
  block:
    - name: Ensure user's "~/.bashrc.d" directory exists
      ansible.builtin.file:
        path: "/home/{{ ansible_user_id }}/.bashrc.d"
        mode: '0744'
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_id }}"
        state: directory

    - name: Copy bash configuration files for user
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_id }}"
      loop:
        - src: files/bashrc
          dest: "/home/{{ ansible_user_id }}/.bashrc"
        - src: files/bash_profile
          dest: "/home/{{ ansible_user_id }}/.bash_profile"
        - src: files/bash_logout
          dest: "/home/{{ ansible_user_id }}/.bash_logout"
        - src: files/bashrc.d/
          dest: "/home/{{ ansible_user_id }}/.bashrc.d/"

    - name: Symlink "git-prompt.sh" for user
      ansible.builtin.file:
        src: /usr/share/git-core/contrib/completion/git-prompt.sh
        dest: "/home/{{ ansible_user_id }}/.bashrc.d/git-prompt.sh"
        state: link
  become: true
  become_user: "{{ ansible_user_id }}"
  tags:
    - user
    - configuration
# }}}

# {{{ Configure root's bash
- name: Configure root's bash
  block:
    - name: Ensure root's "/root/.bashrc.d" directory exists
      ansible.builtin.file:
        path: "/root/.bashrc.d"
        mode: '0744'
        owner: root
        group: root
        state: directory

    - name: Copy bash configuration files for root
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
      loop:
        - src: files/bashrc
          dest: "/root/.bashrc"
        - src: files/bash_profile
          dest: "/root/.bash_profile"
        - src: files/bash_logout
          dest: "/root/.bash_logout"
        - src: files/bashrc.d/
          dest: "/root/.bashrc.d/"

    - name: Symlink "git-prompt.sh" for root
      ansible.builtin.file:
        src: /usr/share/git-core/contrib/completion/git-prompt.sh
        dest: "/root/.bashrc.d/git-prompt.sh"
        state: link
  become: true
  become_user: root
  tags:
    - root
    - configuration
# }}}

# vim: fdm=marker
