---

- name: Configure bash
  block:
    - name: Copy bash configuration files
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_id }}"
      loop:
        - src: files/bashrc
          dest: "/home/{{ ansible_user_id }}/.bashrc"
        - src: files/bash_aliases
          dest: "/home/{{ ansible_user_id }}/.bash_aliases"
        - src: files/bash_profile
          dest: "/home/{{ ansible_user_id }}/.bash_profile"
  become: true
  become_user: "{{ ansible_user_id }}"
  tags:
    - configuration
