---

- include_tasks: _bash.yaml
  loop:
    - become_user: "{{ ansible_user_id }}"
      home_path: "/home/{{ ansible_user_id }}"
      directory_mode: '0744'
      mode: '0644'
    - become_user: root
      home_path: /root
      directory_mode: '0700'
      mode: '0600'
  loop_control:
    loop_var: outer_item
  tags:
    - configuration
