---

- name: Configure bash
  block:
    - name: Copy bash configuration files
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_id }}"
      loop:
        - src: files/bashrc
          dest: "/home/{{ ansible_user_id }}/.bashrc"
        - src: files/bash_aliases
          dest: "/home/{{ ansible_user_id }}/.bash_aliases"
        - src: files/bash_profile
          dest: "/home/{{ ansible_user_id }}/.bash_profile"
        - src: files/bash-prompt.sh
          dest: "/home/{{ ansible_user_id }}/.bash-prompt.sh"

    - name: Symlink "git-prompt.sh"
      ansible.builtin.file:
        src: /usr/share/git-core/contrib/completion/git-prompt.sh
        dest: "/home/{{ ansible_user_id }}/.git-prompt.sh"
        state: link
  become: true
  become_user: "{{ ansible_user_id }}"
  tags:
    - configuration
