---

- name: Set up doom emacs
  block:
    - name: Clone Doom Emacs repo
      ansible.builtin.git:
        depth: 1
        repo: https://github.com/doomemacs/doomemacs
        dest: "/home/{{ ansible_user_id }}/.emacs.d"
        clone: yes
        update: no

    - name: Ensure "~/.doom.d" and "~/org" directories exist
      ansible.builtin.file:
        path: "{{ item.path }}"
        mode: '0744'
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_id }}"
        state: directory
      loop:
        - path: "/home/{{ ansible_user_id }}/.doom.d"
        - path: "/home/{{ ansible_user_id }}/org"

    - name: Copy doom emacs configuration
      ansible.builtin.copy:
        src: files/doom.d/
        dest: "/home/{{ ansible_user_id }}/.doom.d/"
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_id }}"
  become: true
  become_user: "{{ ansible_user_id }}"
  tags:
    - configuration
