---

- name: Configure git user.name
  community.general.git_config:
    name: user.name
    scope: global
    value: "{{ git_username }}"

- name: Configure git user.email
  community.general.git_config:
    name: user.email
    scope: global
    value: "{{ git_email }}"

- name: Configure git core.editor
  community.general.git_config:
    name: core.editor
    scope: global
    value: "{{ git_editor }}"


- name: Configure init.defaultBranch
  community.general.git_config:
    name: init.defaultBranch
    scope: global
    value: "{{ git_default_branch }}"
