---

- name: Set up (neo)vim configuration
  block:
    # {{{ Ensure directories exist
    - name: Ensure (neo)vim directories exist
      ansible.builtin.file:
        path: "{{ item.path }}"
        mode: '0744'
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_id }}"
        state: directory
      loop:
        - path: "/home/{{ ansible_user_id }}/.config/nvim"
        - path: "/home/{{ ansible_user_id }}/.vim"
        - path: "/home/{{ ansible_user_id }}/vimwiki"
    # }}}

    # {{{ Copy configuration files
    - name: Copy (neo)vim configuration files
      ansible.builtin.copy:
        src: files/config/nvim/
        dest: "/home/{{ ansible_user_id }}/.config/nvim/"
        mode: '0644'
        directory_mode: '0744'
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_id }}"
    # }}}

    # {{{ Symlink configuration files for vim
    - name: Symlink configuration files for vim
      ansible.builtin.file:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        state: link
        force: true
      loop:
        - src: "/home/{{ ansible_user_id }}/.config/nvim/init.vim"
          dest: "/home/{{ ansible_user_id }}/.vimrc"
        - src: "/home/{{ ansible_user_id }}/.config/nvim/config"
          dest: "/home/{{ ansible_user_id }}/.vim/config"
        - src: "/home/{{ ansible_user_id }}/.config/nvim/coc-settings.json"
          dest: "/home/{{ ansible_user_id }}/.vim/coc-settings.json"
    # }}}
  become: true
  become_user: "{{ ansible_user_id }}"
  tags:
    - configuration

# vim: fdm=marker
