---

- name: Set up (neo)vim configuration
  block:
    - name: Install (neo)vim packages
      ansible.builtin.dnf:
        name:
          - vim
          - neovim
          - "{{ python_nvim }}"
      become: true
      become_user: root

    - name: Ensure "~/.vim" and "~/.config/nvim" directory exists
      ansible.builtin.file:
        dest: "{{ item.dest }}"
        mode: '0744'
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_id }}"
        state: directory
      loop:
        - dest: "/home/{{ ansible_user_id }}/.vim"
        - dest: "/home/{{ ansible_user_id }}/.config/nvim"
      become: true
      become_user: "{{ ansible_user_id }}"
    
    - name: Copy (neo)vim configuration files
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_id }}"
      loop:
        - src: files/config/nvim/config/
          dest: "/home/{{ ansible_user_id }}/.vim/config/"
        - src: files/config/nvim/init.vim
          dest: "/home/{{ ansible_user_id }}/.vimrc"
        - src: files/config/nvim/
          dest: "/home/{{ ansible_user_id }}/.config/nvim/"
      become: true
      become_user: "{{ ansible_user_id }}"
  tags:
    - configuration
