---

- name: Set up ssh configuration
  block:
    # {{{ Ensure directories exist
    - name: Ensure "~/.ssh" directory exists
      ansible.builtin.file:
        path: "/home/{{ ansible_user_id }}/.ssh"
        mode: '0700'
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_id }}"
        state: directory
    # }}}

    # {{{ Copy configuration
    - name: Copy ssh configuration
      ansible.builtin.copy:
        src: files/ssh/config
        dest: "/home/{{ ansible_user_id }}/.ssh/config"
        mode: '0600'
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_id }}"
    # }}}
  become: true
  become_user: "{{ ansible_user_id }}"
  tags:
    - configuration
