---

- name: Set up vim configuration
  block:
    - name: Ensure "~/.vim" directory exists
      ansible.builtin.file:
        dest: "/home/{{ ansible_user_id }}/.vim"
        mode: '0744'
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_id }}"
        state: directory
    
    - name: Copy vim configuration files
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_id }}"
      loop:
        - src: files/config/nvim/config/
          dest: "/home/{{ ansible_user_id }}/.vim/config/"
        - src: files/config/nvim/init.vim
          dest: "/home/{{ ansible_user_id }}/.vimrc"
  become: true
  become_user: "{{ ansible_user_id }}"
  tags:
    - configuration
