---

- name: Add 1password repo
  ansible.builtin.yum_repository:
    name: 1password
    description: 1Password Stable Channel
    baseurl: https://downloads.1password.com/linux/rpm/stable/$basearch
    gpgkey: https://downloads.1password.com/linux/keys/1password.asc
    gpgcheck: true
    enabled: true
  become: true
  become_user: root
