---

- name: Add 1password repo
  ansible.builtin.yum_repository:
    name: 1password
    description: 1Password Stable Channel
    baseurl: "https://downloads.1password.com/linux/rpm/stable/{{ ansible_architecture }}"
    enabled: true
    gpgcheck: true
    gpgkey: https://downloads.1password.com/linux/keys/1password.asc

