---

- name: Add brave-browser repo
  community.general.zypper_repository:
    name: brave-browser
    description: Brave Browser Release Channel
    repo: https://brave-browser-rpm-release.s3.brave.com/{{ ansible_architecture }}
    auto_import_keys: true
    state: present

