---

- name: Add vscode repo
  ansible.builtin.yum_repository:
    name: code
    description: Visual Studio Code 
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    enabled: true
    skip_if_unavailable: true
    gpgcheck: true
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc
