---

#
# 1password
#
- import_tasks: 1password.yaml

#
# brave
#
- import_tasks: brave-browser.yaml

#
# microsoft
#
- import_tasks: vscode.yaml
- import_tasks: ms-teams.yaml

#
# flathub
#
- import_tasks: flathub.yaml
