---

- name: Add ms-teams repo
  ansible.builtin.yum_repository:
    name: ms-teams
    description: Microsoft Teams
    baseurl: https://packages.microsoft.com/yumrepos/ms-teams
    auto_import_keys: true
    state: present

- name: Remove teams repo
  ansible.builtin.yum_repository:
    name: teams
    baseurl: https://packages.microsoft.com/yumrepos/ms-teams
    state: absent

