---

- name: Add rpmfusion repos
  ansible.builtin.yum_repository:
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    metalink: "{{ item.metalink }}"
    metadata_expire: "{{ item.metadata_expire }}"
    gpgkey: "{{ item.gpgkey }}"
    gpgcheck: true
    enabled: true
  loop:
    - name: rpmfusion-free
      description: RPM Fusion for Fedora $releasever - Free
      metalink: https://mirrors.rpmfusion.org/metalink?repo=free-fedora-$releasever&arch=$basearch
      metadata_expire: 1209600 # 14 days in seconds
      gpgkey: file://etc/pki-rpm-gpg/RPM-GPG-KEY-rpmfusion-free-fedora-$releasever
    - name: rpmfusion-free-updates
      description: RPM Fusion for Fedora $releasever - Free - Updates
      metalink: https://mirrors.rpmfusion.org/metalink?repo=free-fedora-updates-released-$releasever&arch=$basearch
      metadata_expire: 21600 # 6 hours in seconds
      gpgkey: file://etc/pki-rpm-gpg/RPM-GPG-KEY-rpmfusion-free-fedora-$releasever
    - name: rpmfusion-nonfree
      description: RPM Fusion for Fedora $releasever - Nonfree
      metalink: https://mirrors.rpmfusion.org/metalink?repo=nonfree-fedora-$releasever&arch=$basearch
      metadata_expire: 1209600 # 14 days in seconds
      gpgkey: file://etc/pki-rpm-gpg/RPM-GPG-KEY-rpmfusion-nonfree-fedora-$releasever
    - name: rpmfusion-nonfree-updates
      description: RPM Fusion for Fedora $releasever - Nonfree - Updates
      metalink: https://mirrors.rpmfusion.org/metalink?repo=nonfree-fedora-updates-released-$releasever&arch=$basearch
      metadata_expire: 21600 # 6 hours in seconds
      gpgkey: file://etc/pki-rpm-gpg/RPM-GPG-KEY-rpmfusion-nonfree-fedora-$releasever
