---

- name: Install 1password package
  ansible.builtin.dnf:
    name: 1password
    state: latest

- name: Install 1password-cli package
  ansible.builtin.dnf:
    name: 1password-cli
    state: latest
