---

- name: Install development packages
  ansible.builtin.dnf:
    name:
      - "@Development tools"
      - llvm
      - clang
      - clang-devel
      - java-latest-openjdk
      - java-latest-openjdk-devel
      - nodejs
      - npm
      - python
      - python-devel
      - python-flake8
      - python-black
    state: latest
  become: true
  become_user: root
  tags:
    - packages
