---

- name: Install extra packages
  ansible.builtin.dnf:
    name:
      - dconf
      - gnome-tweaks

      - 1password
      - brave-browser
      - steam

      - tmux

      - vim
      - neovim
      - emacs
      - code

      - texlive-scheme-full

      - libtree-sitter

      - llvm
      - clang
      - clang-devel

      - java-latest-openjdk
      - java-latest-openjdk-devel

      - nodejs
      - npm

      - python
      - python-devel
      - python-flake8
      - python-black
      - python-psutil
      - python-tmuxp
      - "{{ python_nvim }}"

      - ripgrep
      - "{{ fd_find }}"
    state: latest
  become: true
  become_user: root
  tags:
    - packages
