---

- name: Install font packages
  ansible.builtin.dnf:
    name:
      - adobe-source-code-pro-fonts
      - dejavu-sans-fonts
      - dejavu-sans-mono-fonts
      - dejavu-serif-fonts
      - gnu-free-fonts-common
      - gnu-free-mono-fonts
      - gnu-free-sans-fonts
      - gnu-free-serif-fonts
      - levien-inconsolata-fonts
      - liberation-fonts-common
      - liberation-mono-fonts
      - liberation-sans-fonts
      - liberation-serif-fonts
      - mozilla-fira-mono-fonts
      - msimonson-anonymouspro-fonts
      - overpass-fonts
      - terminus-fonts
    state: latest
  become: true
  become_user: root
  tags:
    - packages
