---

- name: Install group packages
  ansible.builtin.dnf:
    name:
      - "@core"
      - "@development tools"
      - "@c development tools and libraries"
      - "@rpm development tools"
      - "@virtualization"
    state: present
  become: true
  become_user: root
  tags:
    - packages
