---

- name: Install python packages
  ansible.builtin.dnf:
    name:
      - python
      - python-devel
      - python-psutil # Required by ansible dconf
      - "{{ python_nvim }}"
    state: latest
