---

- name: Modify dconf settings
  community.general.dconf:
    key: "{{ dconf_setting.key }}"
    value: "{{ dconf_setting.value | string }}"
    state: present
  loop: "{{ dconf_settings }}"
  loop_control:
    loop_var: dconf_setting
    label: "{{ dconf_setting.key }}"

# vim: ft=yaml.ansible
