---

- name: Remove unwanted repositories
  when: ansible_distribution == "Fedora"
  become: true
  ansible.builtin.yum_repository:
    name: "{{ repo.name }}"
    state: absent
  loop: "{{ unwanted_repositories }}"
  loop_control:
    loop_var: repo
    label: "{{ repo.name }}"
  notify: dnf-clean-metadata

- name: Remove unwanted repositories
  when: ansible_distribution == "OpenSuse"
  become: true
  community.general.zypper_repository:
    name: "{{ repo.name }}"
    state: absent
  loop: "{{ unwanted_repositories }}"
  loop_control:
    loop_var: repo
    label: "{{ repo.name }}"

# vim: ft=yaml.ansible
