---

- name: Enable copr repositories
  when: ansible_facts['distribution'] == "Fedora"
  become: true
  community.general.copr:
    host: "{{ repo.host }}"
    name: "{{ repo.name }}"
    state: enabled
  loop: "{{ copr_repositories }}"
  loop_control:
    loop_var: repo
    label: "{{ repo.name }}"

# vim: ft=yaml.ansible
