---

- name: Import rpm keys
  when: ansible_distribution == "Fedora"
  become: true
  ansible.builtin.rpm_key:
    key: "{{ repo.key }}"
    state: present
  loop: "{{ rpmfusion_repositories + misc_repositories }}"
  loop_control:
    loop_var: repo
    label: "{{ repo.key }}"

# vim: ft=yaml.ansible
