---

- name: Add miscellaneous repositories
  when: ansible_facts['distribution'] == "Fedora"
  become: true
  ansible.builtin.yum_repository:
    name: "{{ repo.name }}"
    description: "{{ repo.description }}"
    baseurl: "{{ repo.baseurl }}"
    skip_if_unavailable: "{{ repo.skip_if_unavailable }}"
    gpgkey: "{{ repo.gpgkey }}"
    gpgcheck: true
    enabled: true
    state: present
  loop: "{{ misc_repositories }}"
  loop_control:
    loop_var: repo
    label: "{{ repo.description }}"

- name: Add miscellaneous repositories
  when: ansible_facts['distribution'] == "OpenSuse"
  become: true
  community.general.zypper_repository:
    name: "{{ repo.name }}"
    description: "{{ repo.description }}"
    repo: "{{ repo.baseurl }}"
    auto_import_keys: true
    enabled: true
    state: present
  loop: "{{ misc_repositories }}"
  loop_control:
    loop_var: repo
    label: "{{ repo.description }}"

# vim: ft=yaml.ansible
