---

- name: Add miscellaneous repositories
  when: ansible_distribution == "Fedora"
  become: true
  ansible.builtin.yum_repository:
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    baseurl: "{{ item.baseurl }}"
    skip_if_unavailable: "{{ item.skip_if_unavailable }}"
    gpgkey: "{{ item.gpgkey }}"
    gpgcheck: true
    enabled: true
  loop: "{{ misc_repos }}"

# vim: ft=yaml.ansible
