---

- name: Add rpmfusion repositories
  when: ansible_facts['distribution'] == "Fedora"
  become: true
  ansible.builtin.yum_repository:
    name: "{{ repo.name }}"
    description: "{{ repo.description }}"
    metalink: "{{ repo.metalink }}"
    metadata_expire: "{{ repo.metadata_expire }}"
    gpgkey: "{{ repo.gpgkey }}"
    gpgcheck: true
    enabled: true
  loop: "{{ rpmfusion_repositories }}"
  loop_control:
    loop_var: repo
    label: "{{ repo.description }}"

# vim: ft=yaml.ansible
