---

- name: Configure git
  community.general.git_config:
    name: "{{ item.name }}"
    scope: "{{ item.scope }}"
    value: "{{ item.value }}"
  loop: "{{ git_configuration }}"
  loop_control:
    label: "{{ item.name }}"

# vim: ft=yaml.ansible
