---

dependencies: []

galaxy_info:
  author: Pedro Avalos
  description: Set up system information

  platforms:
    - name: Fedora
      versions:
        - all

  galaxy_tags: []

# vim: ft=yaml.ansible
