---

- name: Clone pavalos6401/nvim repo for neovim
  ansible.builtin.git:
    repo: https://github.com/pavalos6401/nvim.git
    dest: "{{ nvim_dir }}"

- name: Clone pavalos6401/nvim repo (branch=vimscript) for vim
  ansible.builtin.git:
    repo: https://github.com/pavalos6401/nvim.git
    dest: "{{ vim_dir }}"
    version: vimscript
  notify:
    - Symlink vimrc

# vim: ft=yaml.ansible
