---

- name: Ensure directories exist
  ansible.builtin.file:
    path: "{{ item.path }}"
    mode: '0744'
    state: directory
  loop:
    - path: "{{ nvim_dir }}"
    - path: "{{ vim_dir }}"
    - path: "{{ vimwiki_dir }}"
  loop_control:
    label: "{{ item.path }}"

- name: Copy configuration files for nvim
  ansible.builtin.copy:
    src: nvim/
    dest: "{{ nvim_dir }}/"
    mode: '0644'
    directory_mode: '0744'

- name: Copy configuration files for vim
  ansible.builtin.copy:
    src: vim/
    dest: "{{ vim_dir }}/"
    mode: '0644'
    directory_mode: '0744'

- name: Symlink init.vim to vimrc
  ansible.builtin.file:
    src: "{{ vim_dir }}/init.vim"
    dest: "{{ vimrc }}"
    state: link
    force: true

# vim: ft=yaml.ansible
